### ISSUE TITLE
Chennaipy Logo needs to be added

### ISSUE THREAD

**Issue by gnurenga** [Chennaipy/website#128]
- We need to add chennaipy logo in main page.
- We need to use the logo which was selected using Members polling.

**Comment by kskrishnasangeeth** [comment]
:+1:

**Comment by bravegnu** [comment]
Yep, that's a long pending task.

**Comment by gnurenga** [comment]
I just added top:250px in pure.css file, so that i got some space at the top in sidebar, Shall we keep the logo at the top.
```
.sidebar {
    position: fixed;
    top: 250px;
    bottom: 0;
    width: 25%;
    margin-left: -25%;
    
}
```
![screenshot from 2016-10-31 16 31 41](https://cloud.githubusercontent.com/assets/3196294/19852285/70985668-9f88-11e6-9fe4-3408f80489f4.png)

**Comment by arvnedumaran** [comment]
Instead of the whitespace for the logo, can we just put it on top of the BG image? Like the attached image? 

![logo](https://cloud.githubusercontent.com/assets/11900442/21879551/81197da8-d8bf-11e6-8ed0-dd65a605b4b1.jpeg)

**Comment by shrayasr** [comment]
> Instead of the whitespace for the logo, can we just put it on top of the BG image? Like the attached image? Maybe, if the text on the image is lighter (white?) it would look more vibrant over the background. Just a thought :)

This looks nice! Yes can do. The text needs to be in white though.

Paging @vengatlnx for the change

**Comment by arvnedumaran** [comment]
It's my first time contributing here, I pushed the pelican config and the cropped low-res version of the logo (Can be updated when a different, high-res version is available) to this repo and the changes to the theme to the separate repo. I've opened PRs for both. Is that the procedure followed here?

**Comment by shrayasr** [comment]
> It's my first time contributing here, I pushed the pelican config and the cropped low-res version of the logo (Can be updated when a different, high-res version is available) to this repo and the changes to the theme to the separate repo. I've opened PRs for both. Is that the procedure followed here?

You're awesome :sparkles: . That is the way. 

I'm +1 on it. Its a great start compared to where we are currently and we can improve when @vengatlnx gives us the logo with the text in White. Let one of the others from the @Chennaipy/web-team +1 on it and we'll merge and deploy. 

Thanks much for your contribution. :shipit:

**Comment by shrayasr** [comment]
> Is that the procedure followed here?

A small nitpick tho: When sending PRs, a good practice would be to reference the issue that its fixing in the PR's commit message / description. This allows for easy discoverability.

I've done it for you this time around though :+1:

**Comment by vengatlnx** [comment]
Hi Everyone,
    Hereby I've attached the source link for chennaipy logo.

https://github.com/vengatlnx/Chennaipy-logo

Sorry for the delay.


On Thu, Jan 12, 2017 at 2:22 PM, Shrayas Rajagopal <notifications@github.com
