### ISSUE TITLE
Mailing list guidelines page

### ISSUE THREAD

**Issue by Rengaraj** [Chennaipy/website#29]
We need to have a mailing list guidlines page to educate people who are new to open source community.

**Comment by shrayasr** [comment]
@kirang89 @Rengaraj @bravegnu should we keep this issue open?

**Comment by kirang89** [comment]
Since you've already merged it, I don't see any reason to keep this open. @bravegnu ?

**Comment by shrayasr** [comment]
Yeah, can open another issue/PR when we decide to improve it
