### ISSUE TITLE
Rename repo to chennaipy.org

### ISSUE THREAD

**Issue by shrayasr** [Chennaipy/website#43]
Why don't we rename the repo to chennaipy.org? For one, it would make it self explanatory when forking as opposed to just "website".

**Comment by bravegnu** [comment]
Naming the project chennaipy/website looks more appropriate than chennaipy/chennaipy.org Whoever forks it, is free to call it whatever they want.

**Comment by shrayasr** [comment]
The process of renaming it to whatever they want is one extra step with adoption, no? As opposed to just forking it and it being called _chennaipy.org_. 

Just calling it _website_ seemed kind of bland to me as well.

**Comment by bravegnu** [comment]
It's unfortunate that GitHub doesn't allow you to choose a name while forking.

If name collision is the problem, how about "chennaipy-website"?

**Comment by shrayasr** [comment]
> It's unfortunate that GitHub doesn't allow you to choose a name while forking.

Yeah that'd have been nice. Its really not a hassle to rename after forking though. 

> If name collision is the problem, how about "chennaipy-website"?

This just becomes redundant. Lets leave it at _website_ for now then
