### ISSUE TITLE
Adding disqus comments to Chennaipy website

### ISSUE THREAD

**Issue by kskrishnasangeeth** [Chennaipy/website#48]
There is already a file called <code>disqus.html</code> and Pure Pelican supports adding disqus comments . Unless we want to purposefully avoid comments , i think it will be better to add some sort of commenting system.

I have tried in my local and got disqus configured. Please let me know what you guys think .

![chennaipy](https://cloud.githubusercontent.com/assets/1977850/5652191/031780be-96d4-11e4-9e9e-defc941c5422.png)

**Comment by shrayasr** [comment]
Closing this as per discussion on #49
