### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by shrayasr** [Chennaipy/website#51]
Maybe a good thing to start doing to understand the traffic on the website and where it is going. Could be useful to make decisions like with #49

**Comment by kskrishnasangeeth** [comment]
I think this is pretty straight forward. We would need to update <code>pelicanconf.py</code> and add entry for <code>GOOGLE_ANALYTICS</code> . If there is a default email id for chennaipy, we could use it for setting it up.

**Comment by shrayasr** [comment]
Yeah, but **do** we want to do this? @bravegnu

**Comment by bravegnu** [comment]
Should be useful.

**Comment by shrayasr** [comment]
Allright then. Do we have an email ID for chennaipy that we can use for this?

**Comment by bravegnu** [comment]
I can create something like webmaster@chennaipy.org. Will that be OK?

**Comment by shrayasr** [comment]
Should be fine I think? I don't think it is absolutely **necessary** to have a Google account

@kskrishnasangeeth would you like to take this up?

**Comment by kskrishnasangeeth** [comment]
I think we need google account setup. We could use the above mentioned mail id to setup , but then there will be some sort of verification process that follows. 

I would like to takeup if it is okay to share the creds.

**Comment by shrayasr** [comment]
Yeah, they'll send a verification to the same email ID. 

Since it is a community thing, I don't think it is a problem to share the credentials if @bravegnu is ok with it. We can keep it in a private gist.

**Comment by kskrishnasangeeth** [comment]
@shrayasr Alrighty. :+1:  I have tried to create a google account with <code>webmaster@chennaipy.org</code> .  If @bravegnu is okay with it , please verify it.
