### ISSUE TITLE
why hosting, when one can use gh-pages ?

### ISSUE THREAD

**Issue by igauravsehrawat** [Chennaipy/website#65]

**Comment by bravegnu** [comment]
Of course there are pros and cons with every approach. See http://www.kevinsweet.com/pros-cons-github-pages/

**Comment by igauravsehrawat** [comment]
so is chennaipy  using the cons described in the link ?

**Comment by bravegnu** [comment]
May be not now. But we would like to support things like HTTPS in the future(#53) for example.

**Comment by bravegnu** [comment]
BTW, why would we want to fix something that is not broken?

**Comment by igauravsehrawat** [comment]
I was suggesting open source alternatives , that's all.

**Comment by bravegnu** [comment]
Hmmm ... You mean "free" (as in zero cost) alternatives. AFAIK neither the GitHub stack nor the Heroku stack is open source. :-)

**Comment by bravegnu** [comment]
@igauravsehrawat  We also do email hosting apart from web hosting on hostgator. Which is not possible in the alternatives mentioned. So if you are convinced let's close this.

**Comment by igauravsehrawat** [comment]
yeah sure.
