### ISSUE TITLE
[IMPORTANT] Build hasn't gone through for latest PR

### ISSUE THREAD

**Issue by shrayasr** [Chennaipy/website#75]
@bravegnu,

Travis indicates that the build exited with a `0` status but on [further inspection](https://travis-ci.org/Chennaipy/website/builds/56522952#L270) it looks like there was some problem with the `rsync` upload to the server.

Could you please check on this?

**Comment by shrayasr** [comment]
:bell: @bravegnu ?

**Comment by bravegnu** [comment]
Fixed by https://github.com/Chennaipy/website/commit/a314a4154c8c87a4683059f5ea33752409178246 For some unknown reason, the second rsync succeeds. Will raise this with hostgator, meanwhile this workaround should do.

**Comment by shrayasr** [comment]
Wow that's weird. All right please do.
